In [57]:
import pandas as pd

In [58]:
stk_data=pd.read_csv("Tatacoffee13_21.csv")

In [59]:
stk_data=stk_data[(stk_data["Date"]>="2020-07-01")&(stk_data["Date"]<="2021-12-28")]

In [60]:
stk_data

            Date    Open    High     Low   Close
1851  2020-07-01   81.50   82.70   81.05   81.95
1852  2020-07-02   82.25   82.70   81.55   81.90
1853  2020-07-03   82.05   85.45   82.05   84.35
1854  2020-07-06   85.80   87.85   85.05   86.60
1855  2020-07-07   86.70   87.00   85.05   85.65
...          ...     ...     ...     ...     ...
2220  2021-12-22  202.90  207.80  201.35  205.00
2221  2021-12-23  206.00  206.85  202.05  202.95
2222  2021-12-24  203.90  203.90  199.35  201.00
2223  2021-12-27  200.00  222.00  196.00  218.35
2224  2021-12-28  219.65  220.45  211.55  212.35

[374 rows x 5 columns]

In [61]:
# preprocessing
from sklearn.preprocessing import MinMaxScaler
Ms=MinMaxScaler()
data1=Ms.fit_transform(stk_data[["Open","High","Low","Close"]])
print("Len:",data1.shape)

Len: (374, 4)

In [62]:
data1=pd.DataFrame(data1, columns=['Open','High','Low','Close'])

In [63]:
data1

         Open      High       Low     Close
0    0.015432  0.015482  0.021817  0.025032
1    0.020062  0.015482  0.025073  0.024715
2    0.018827  0.031250  0.028330  0.040241
3    0.041975  0.045011  0.047867  0.054499
4    0.047531  0.040138  0.047867  0.048479
..        ...       ...       ...       ...
369  0.764815  0.732798  0.805275  0.804816
370  0.783951  0.727351  0.809834  0.791825
371  0.770988  0.710436  0.792250  0.779468
372  0.746914  0.814220  0.770433  0.889417
373  0.868210  0.805333  0.871703  0.851394

[374 rows x 4 columns]

In [64]:
# Training and Test data split
training_size=round(len(data1)*0.80)
print(training_size)
X_train=data1[:training_size]
X_test=data1[training_size:]
print("X_train length:",X_train.shape)
print("X_test length:",X_test.shape)
Y_train=data1[:training_size]
Y_test=data1[training_size:]
print("Y_train length:", Y_train.shape)
print("Y_test length:",Y_test.shape)

299
X_train length: (299, 4)
X_test length: (75, 4)
Y_train length: (299, 4)
Y_test length: (75, 4)

In [65]:
import warnings
warnings.filterwarnings("ignore")

In [66]:
# Creating a dictionary 
performance={"Model":[],"RMSE":[],"MaPe":[],"Lag":[],"Test":[]}

In [67]:
# Defining the function cominbation with two parameters, dataset(values) and list(columnnames:keys) to be passed while calling the function
def cominbation(dataset,listt):
    # print the listt(i.e, key values or column names)
    print(listt)
    # Creating the table with passed keys and values i.e data and column names
    datasetTwo=dataset[listt]
    print(datasetTwo)
    # Here we are determining the number of samples we are going to take for test and based on that training samples are calculated
    test_obs=28
    # Subtracting test samples from overall data to determine the training samples
    train=datasetTwo[:-test_obs]
    # Test sample determined is taken for testing(here its 28)
    test=datasetTwo[-test_obs:]
    print("Train length:",train.shape)
    print("Test length:", test.shape)
    # import VAR module from statsmodels
    from statsmodels.tsa.api import VAR
    # here we have the lag orders from 1 to 10 to find aic and bic for each lag-order
    for i in [1,2,3,4,5,6,7,8,9,10]:
    # passing the training data to the model
        model=VAR(train)
        results=model.fit(i)
        print("Order=", i)
        print("AIC:",results.aic)
        print("BIC:",results.bic)
    # select_order is used to test the model for each lag and keeping max lag as 12
    x=model.select_order(maxlags=12)
    # here we want to select the lag which has lowest aic value
    order=x.selected_orders["aic"]
     # Fitting the model with the best order and storing the results of them in result
    result = model.fit(order)
    result.summary()
    # Here we taking the lagged_values from training data based on the selected order above(if the order is selected as 1 then only the last row of the 
    # training data will be taken to lagged_values)
    lagged_Values=train.values[-order:]
    print(lagged_Values)
    print("order =", order)
    print("train values shape =",train.values.shape)
    print("train shape =", train.shape)
    print("lagged_values shape =", lagged_Values.shape)
    # Here we got shape mismatch issue as the forecast expects 2 d array and the lagged values are 1 d array as we have 4 variables we  have re-shaped
    # this way so the forecast method doesn't throw a value error
    lagged_Values = lagged_Values.reshape(order, train.shape[1])
    print("order =", order)
    print("result.k_ar =", result.k_ar)
    print("train shape =", train.shape)
    print("lagged_values shape =", lagged_Values.shape)
    # for the taken lagged_values(training input) we are predicting the next 28 values in the time series
    pred=result.forecast(y=lagged_Values, steps=28)
    # Creating the table for the predicted series 
    preds=pd.DataFrame(pred,columns=listt)
    print(preds)
    # saving the result to csv file
    preds.to_csv("varforecasted_{}.csv".format(test_obs))
    # evaluating the model using mean_square_error
    from sklearn.metrics import mean_squared_error
    # passing test data and training data to determine rmse
    rmse= round(mean_squared_error(test,pred,squared=False),4)
    # mean absolute percentage error to check the accuracy of the model
    from sklearn.metrics import mean_absolute_percentage_error
    # passing the test data values and predicted values to determine the prediction accuracy
    mape=mean_absolute_percentage_error(test,pred)
    # Now appending the list with the values obtained one by one, i.e model(variables used to train the model)
    # RMSE - root mean square for each combination we give
    # Mape- for each combination we give
    # Lag- which lag is selected for each combination
    # Test- how many test observation are used - here it is 28
    performance["Model"].append(listt)
    performance["RMSE"].append(rmse)
    performance["MaPe"].append(mape)
    performance["Lag"].append(order)
    performance["Test"].append(test_obs)
    perf=pd.DataFrame(performance)
    return perf,result,pred

In [68]:
# TO get all the combinations in one function the below code can be used
listt = [
    ['Close', 'High'],
    ['Close', 'High', 'Open'],
    ['Close', 'High', 'Open', 'Low']
]

for combination in listt:
    perf, result, pred = cominbation(data1, combination)

['Close', 'High']
        Close      High
0    0.025032  0.015482
1    0.024715  0.015482
2    0.040241  0.031250
3    0.054499  0.045011
4    0.048479  0.040138
..        ...       ...
369  0.804816  0.732798
370  0.791825  0.727351
371  0.779468  0.710436
372  0.889417  0.814220
373  0.851394  0.805333

[374 rows x 2 columns]
Train length: (346, 2)
Test length: (28, 2)
Order= 1
AIC: -16.105309866465785
BIC: -16.038465615734808
Order= 2
AIC: -16.21327111752211
BIC: -16.101624557714743
Order= 3
AIC: -16.197908668310685
BIC: -16.041266609242687
Order= 4
AIC: -16.201617469235938
BIC: -15.99978532518001
Order= 5
AIC: -16.218974759316648
BIC: -15.971756534975777
Order= 6
AIC: -16.207183347961475
BIC: -15.914381624261871
Order= 7
AIC: -16.2021549151692
BIC: -15.863570834870046
Order= 8
AIC: -16.187579554534366
BIC: -15.803012807651461
Order= 9
AIC: -16.172416633412645
BIC: -15.74166544245303
Order= 10
AIC: -16.153474205957682
BIC: -15.676335310962282
[[0.89797212 0.82712156]
 [0.90430925 0.83572248]
 [0.93536122 0.84747706]
 [0.93029151 0.8543578 ]
 [0.95595691 0.86811927]]
order = 5
train values shape = (346, 2)
train shape = (346, 2)
lagged_values shape = (5, 2)
order = 5
result.k_ar = 5
train shape = (346, 2)
lagged_values shape = (5, 2)
       Close      High
0   0.962505  0.889925
1   0.961289  0.891086
2   0.964587  0.891224
3   0.966466  0.894385
4   0.967115  0.894553
5   0.969724  0.895617
6   0.972541  0.898231
7   0.974954  0.900548
8   0.977698  0.902885
9   0.980430  0.905508
10  0.982994  0.907960
11  0.985599  0.910336
12  0.988213  0.912764
13  0.990793  0.915164
14  0.993387  0.917550
15  0.995991  0.919956
16  0.998588  0.922362
17  1.001187  0.924765
18  1.003788  0.927172
19  1.006386  0.929579
20  1.008985  0.931983
21  1.011584  0.934388
22  1.014182  0.936793
23  1.016780  0.939198
24  1.019377  0.941602
25  1.021975  0.944006
26  1.024572  0.946409
27  1.027169  0.948813
['Close', 'High', 'Open']
        Close      High      Open
0    0.025032  0.015482  0.015432
1    0.024715  0.015482  0.020062
2    0.040241  0.031250  0.018827
3    0.054499  0.045011  0.041975
4    0.048479  0.040138  0.047531
..        ...       ...       ...
369  0.804816  0.732798  0.764815
370  0.791825  0.727351  0.783951
371  0.779468  0.710436  0.770988
372  0.889417  0.814220  0.746914
373  0.851394  0.805333  0.868210

[374 rows x 3 columns]
Train length: (346, 3)
Test length: (28, 3)
Order= 1
AIC: -25.75157737846443
BIC: -25.617888877002468
Order= 2
AIC: -25.730268107361255
BIC: -25.495810331765785
Order= 3
AIC: -25.717878030005792
BIC: -25.382216474860083
Order= 4
AIC: -25.72143429080799
BIC: -25.28413131202015
Order= 5
AIC: -25.71824761341485
BIC: -25.17886239667113
Order= 6
AIC: -25.682853054822495
BIC: -25.0409415836349
Order= 7
AIC: -25.668602830945478
BIC: -24.923717854287336
Order= 8
AIC: -25.633197775898346
BIC: -24.784888775421347
Order= 9
AIC: -25.586645920797764
BIC: -24.63445907762388
Order= 10
AIC: -25.539189950218265
BIC: -24.482668111299876
[[0.95595691 0.86811927 0.91358025]]
order = 1
train values shape = (346, 3)
train shape = (346, 3)
lagged_values shape = (1, 3)
order = 1
result.k_ar = 1
train shape = (346, 3)
lagged_values shape = (1, 3)
       Close      High      Open
0   0.960923  0.885404  0.933050
1   0.963541  0.890068  0.937018
2   0.965699  0.892758  0.939489
3   0.967710  0.894855  0.941576
4   0.969669  0.896751  0.943535
5   0.971610  0.898578  0.945450
6   0.973542  0.900380  0.947348
7   0.975470  0.902171  0.949238
8   0.977394  0.903958  0.951124
9   0.979316  0.905741  0.953007
10  0.981235  0.907522  0.954887
11  0.983151  0.909299  0.956764
12  0.985064  0.911075  0.958639
13  0.986975  0.912848  0.960511
14  0.988883  0.914618  0.962380
15  0.990789  0.916386  0.964247
16  0.992692  0.918152  0.966112
17  0.994592  0.919915  0.967973
18  0.996489  0.921675  0.969832
19  0.998384  0.923434  0.971689
20  1.000277  0.925189  0.973543
21  1.002166  0.926943  0.975394
22  1.004053  0.928694  0.977243
23  1.005938  0.930442  0.979089
24  1.007820  0.932188  0.980933
25  1.009699  0.933932  0.982774
26  1.011576  0.935673  0.984613
27  1.013450  0.937412  0.986449
['Close', 'High', 'Open', 'Low']
        Close      High      Open       Low
0    0.025032  0.015482  0.015432  0.021817
1    0.024715  0.015482  0.020062  0.025073
2    0.040241  0.031250  0.018827  0.028330
3    0.054499  0.045011  0.041975  0.047867
4    0.048479  0.040138  0.047531  0.047867
..        ...       ...       ...       ...
369  0.804816  0.732798  0.764815  0.805275
370  0.791825  0.727351  0.783951  0.809834
371  0.779468  0.710436  0.770988  0.792250
372  0.889417  0.814220  0.746914  0.770433
373  0.851394  0.805333  0.868210  0.871703

[374 rows x 4 columns]
Train length: (346, 4)
Test length: (28, 4)
Order= 1
AIC: -35.17143191439903
BIC: -34.94861774529576
Order= 2
AIC: -35.14326374606217
BIC: -34.74133613075565
Order= 3
AIC: -35.103783450467596
BIC: -34.521970088215035
Order= 4
AIC: -35.08146329022057
BIC: -34.31898630156484
Order= 5
AIC: -35.056650582230716
BIC: -34.1127264529292
Order= 6
AIC: -35.0049936263104
BIC: -33.87883315054269
Order= 7
AIC: -34.97082168427591
BIC: -33.66162990711918
Order= 8
AIC: -34.90705948850453
BIC: -33.414035647665
Order= 9
AIC: -34.89181852068216
BIC: -33.21415598747103
Order= 10
AIC: -34.86710440112564
BIC: -33.0039906206674
[[0.95595691 0.86811927 0.91358025 0.97199609]]
order = 1
train values shape = (346, 4)
train shape = (346, 4)
lagged_values shape = (1, 4)
order = 1
result.k_ar = 1
train shape = (346, 4)
lagged_values shape = (1, 4)
       Close      High      Open       Low
0   0.957045  0.880306  0.934315  0.968289
1   0.959312  0.883827  0.933240  0.965088
2   0.961728  0.887790  0.935439  0.965861
3   0.963846  0.890641  0.937767  0.967331
4   0.965837  0.892863  0.939799  0.969016
5   0.967778  0.894832  0.941729  0.970826
6   0.969695  0.896688  0.943620  0.972694
7   0.971599  0.898489  0.945492  0.974586
8   0.973495  0.900265  0.947353  0.976488
9   0.975386  0.902027  0.949207  0.978393
10  0.977274  0.903782  0.951058  0.980297
11  0.979159  0.905532  0.952904  0.982200
12  0.981041  0.907278  0.954748  0.984101
13  0.982920  0.909022  0.956589  0.985999
14  0.984796  0.910762  0.958428  0.987895
15  0.986669  0.912501  0.960263  0.989788
16  0.988540  0.914236  0.962096  0.991678
17  0.990408  0.915969  0.963927  0.993566
18  0.992274  0.917700  0.965754  0.995450
19  0.994136  0.919428  0.967580  0.997332
20  0.995996  0.921154  0.969402  0.999212
21  0.997854  0.922877  0.971222  1.001089
22  0.999709  0.924598  0.973039  1.002963
23  1.001561  0.926316  0.974854  1.004834
24  1.003410  0.928031  0.976666  1.006703
25  1.005257  0.929745  0.978475  1.008568
26  1.007101  0.931456  0.980282  1.010432
27  1.008942  0.933164  0.982086  1.012292

In [69]:
perf

                      Model    RMSE      MaPe  Lag  Test
0             [Close, High]  0.1656  0.200617    5    28
1       [Close, High, Open]  0.1612  0.193862    1    28
2  [Close, High, Open, Low]  0.1587  0.188550    1    28